import type { BusinessInvariant } from '../invariant';

const FRD = 'D:/Kpost Documents/KPOST_FRD_Katchup_v1.9.docx (via docs/business-rules.md § Katchup)';

/**
 * Katchup — the module whose differentiators are the product's reason to exist (subject on every
 * message, recall, confidential copy, per-recipient receipts), so it carries the most rules.
 *
 * Several are `TO_DO` on purpose. The bench asserts the happy path of send/recall/edit but has never
 * asserted the CONSTRAINTS around them — recall only before reading, recall not on copies, the
 * disappear flag being immutable after send. Those are exactly the rules a product breaks quietly,
 * and declaring them is how they stop being invisible.
 */
export const KATCHUP_INVARIANTS: readonly BusinessInvariant[] = [
  {
    invariantId: 'BR-KU-SUBJECT',
    module: 'katchup',
    statement:
      'Every Katchup message carries a Subject; a blank subject is stored as the literal "General", never as an empty value.',
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → BR-KU-SUBJECT` },
    requirements: ['FR-KU-001'],
    actors: ['sender'],
    appliesTo: ['katchup-send-message'],
    preconditions: ['the sender is authenticated', 'a recipient exists'],
    observedStates: ['katchup.message.sent'],
    expected:
      'the sent message read back carries the Subject that was sent; a blank subject reads back as "General"',
    evidence: ['RESPONSE_FIELD', 'READ_BACK'],
    status: 'PARTIAL',
    verifiedBy: 'tests/api/kpost/katchup/feature.spec.ts',
    gap: 'the non-blank subject is asserted on the response; the blank → "General" default is not.',
  },
  {
    invariantId: 'NFR-SEC02',
    module: 'katchup',
    statement:
      'A Confidential Copy recipient is invisible to every other recipient of the same message.',
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → NFR-SEC02; CLAUDE.md §2` },
    requirements: ['NFR-SEC02'],
    actors: ['recipient', 'copy-recipient', 'confidential-copy-recipient'],
    appliesTo: ['katchup-send-message'],
    preconditions: ['three distinct accounts: a TO recipient, a visible Copy and a hidden Copy'],
    expected:
      "the TO and Copy recipients' reads of the message do not name the confidential recipient anywhere",
    evidence: ['CROSS_ACTOR', 'ABSENCE'],
    status: 'VERIFIED',
    verifiedBy: 'tests/api/kpost/katchup/feature.spec.ts',
  },
  {
    invariantId: 'BR-KU-EDIT-SUBJ',
    module: 'katchup',
    statement:
      'Editing a message changes the BODY only: the Subject cannot change, and the message is marked as edited.',
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → BR-KU-EDIT-SUBJ` },
    requirements: ['FR-KU-009'],
    actors: ['sender', 'recipient'],
    appliesTo: ['katchup-send-message'],
    preconditions: ['a message the sender already sent'],
    observedStates: ['katchup.message.edited'],
    expected:
      'after an edit the body differs, the Subject is byte-identical to the original, and the edited marker is present',
    evidence: ['READ_BACK', 'CROSS_ACTOR'],
    status: 'PARTIAL',
    verifiedBy: 'tests/api/kpost/katchup/feature.spec.ts',
    gap: 'the changed body and the edited marker are asserted; Subject immutability is not.',
  },
  {
    invariantId: 'BR-KU-RECALL',
    module: 'katchup',
    statement: "A recalled message is removed from the recipient's view entirely.",
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → BR-KU-RECALL; CLAUDE.md §2 BR-K03` },
    requirements: ['FR-KU-010'],
    actors: ['sender', 'recipient'],
    appliesTo: ['katchup-recall-message'],
    preconditions: ['a message the sender sent and the recipient has not yet read'],
    expected: "the recipient's conversation read no longer contains the message",
    evidence: ['CROSS_ACTOR', 'ABSENCE'],
    status: 'VERIFIED',
    verifiedBy: 'tests/api/kpost/katchup/feature.spec.ts',
  },
  {
    invariantId: 'BR-KU-RECALL-UNREAD',
    module: 'katchup',
    statement: 'Recall is permitted only while the recipient has not yet read the message.',
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → BR-KU-RECALL-UNREAD` },
    requirements: ['FR-KU-010'],
    actors: ['sender'],
    appliesTo: ['katchup-recall-message'],
    preconditions: ['a message the recipient HAS read (the read transition is calibrated)'],
    observedStates: ['katchup.message.read'],
    expected: 'recalling an already-read message is refused',
    evidence: ['REJECTION', 'STATE_TRANSITION'],
    status: 'TO_DO',
  },
  {
    invariantId: 'BR-KU-RECALL-SCOPE',
    module: 'katchup',
    statement: 'Recall is unavailable for copies and for group messages.',
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → BR-KU-RECALL-SCOPE` },
    requirements: ['FR-KU-010'],
    actors: ['sender'],
    appliesTo: ['katchup-recall-message'],
    preconditions: ['a message sent as a Copy, and a message sent to a group'],
    expected: 'recall on a copy or on a group message is refused',
    evidence: ['REJECTION'],
    status: 'TO_DO',
  },
  {
    invariantId: 'BR-KU-DISAPPEAR-READ',
    module: 'katchup',
    statement:
      '"Disappear After Reading" deletes the message when the recipient reads it, with no timer involved.',
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → FR-KU-017..024` },
    requirements: ['FR-KU-017', 'FR-KU-018'],
    actors: ['sender', 'recipient'],
    appliesTo: ['katchup-send-message'],
    preconditions: ['a message sent with isVanished set'],
    observedStates: ['katchup.message.vanishing'],
    expected: 'after the recipient reads it the message is gone for both parties',
    evidence: ['CROSS_ACTOR', 'ABSENCE', 'STATE_TRANSITION'],
    status: 'PARTIAL',
    verifiedBy: 'tests/api/kpost/katchup/feature.spec.ts',
    gap: 'the bench sends both disappearing modes and asserts acceptance; the delete-on-read is not observed.',
  },
  {
    invariantId: 'BR-KU-DISAPPEAR-SCHED',
    module: 'katchup',
    statement:
      '"Disappear As Per Schedule" deletes the message at its scheduled time whether or not it was read.',
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → FR-KU-017..024` },
    requirements: ['FR-KU-017', 'FR-KU-019'],
    actors: ['sender', 'recipient'],
    appliesTo: ['katchup-send-message'],
    preconditions: ['a message sent with a secretMessageExpireTime in the near future'],
    observedStates: ['katchup.message.scheduled-expiry'],
    expected: 'once the scheduled time passes the message is absent even though it was never read',
    evidence: ['ABSENCE', 'STATE_TRANSITION'],
    status: 'TO_DO',
    gap: 'needs a flow that can wait out a real timer, which no current spec supports.',
  },
  {
    invariantId: 'BR-KU-DISAPPEAR-IMMUTABLE',
    module: 'katchup',
    statement: 'The disappearing-message setting cannot be changed after the message is sent.',
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → FR-KU-017..024` },
    requirements: ['FR-KU-017'],
    actors: ['sender'],
    appliesTo: ['katchup-send-message'],
    preconditions: ['a sent disappearing message'],
    expected: 'no edit path alters the disappear flag or its expiry after send',
    evidence: ['READ_BACK', 'REJECTION'],
    status: 'TO_DO',
  },
  {
    invariantId: 'BR-KU-FORWARD-HIDE',
    module: 'katchup',
    statement: 'A hide-source forward does not expose the original sender to the new recipient.',
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → FR-KU-035..038` },
    requirements: ['FR-KU-035', 'FR-KU-036'],
    actors: ['sender', 'recipient'],
    appliesTo: ['katchup-forward-message', 'katchup-forward-message-new'],
    preconditions: ['a received message, forwarded with the source hidden'],
    expected: "the new recipient's read of the forwarded message names no original sender identity",
    evidence: ['CROSS_ACTOR', 'ABSENCE'],
    status: 'TO_DO',
    gap: 'the forward endpoints answer 500 on the test host today (CLAUDE.md 2026-09-13), so the rule cannot yet be exercised.',
  },
  {
    invariantId: 'BR-KU-RECEIPTS',
    module: 'katchup',
    statement:
      'A per-recipient read date and time is recorded, and only once that recipient has actually read the message.',
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → BR-KU-RECEIPTS; SRS-K03` },
    requirements: ['FR-KU-007'],
    actors: ['sender', 'recipient', 'group-member'],
    appliesTo: ['katchup-read-status-group', 'katchup-conversation'],
    preconditions: ['a group message with at least two members'],
    observedStates: [
      'katchup.message.recipient-read-status',
      'katchup.message.recipient-read-time',
      'katchup.message.read-time-recorded',
    ],
    expected:
      'a member who has not read shows no read time; after that member reads, a read time appears for them and not for the others',
    evidence: ['STATE_TRANSITION', 'CROSS_ACTOR'],
    status: 'PARTIAL',
    verifiedBy: 'tests/api/kpost/katchup/feature.spec.ts',
    gap: 'receipts are read back; the before/after transition per member is not asserted.',
    conflict:
      'CONF-KATCHUP-READ-PERSPECTIVE: the Phase 4D calibration found the API conversation read itself performs the read transition, which contradicts the Phase 4B model recording the mechanism as UI. Preserved, not resolved.',
  },
  {
    invariantId: 'BR-KU-DELETE-OWN',
    module: 'katchup',
    statement:
      "Deleting a received message removes it from the deleter's view only; other participants still see it.",
    provenance: { status: 'DOCUMENTED', citation: `${FRD} → BR-KU-DELETE-OWN` },
    requirements: ['FR-KU-020'],
    actors: ['sender', 'recipient'],
    appliesTo: ['katchup-delete-message'],
    preconditions: ['a message both parties can see'],
    observedStates: ['katchup.message.deleted'],
    expected:
      "after one party deletes, that party's read omits it and the other party's still shows it",
    evidence: ['CROSS_ACTOR', 'ABSENCE', 'READ_BACK'],
    status: 'PARTIAL',
    verifiedBy: 'tests/api/kpost/katchup/lifecycle.spec.ts',
    gap: "absence is asserted for the deleter only; the other party's continued visibility is not checked.",
  },
];
